services:
  frontend:
    build:
      context: ./hrms-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./hrms-project:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - db_data:/data/db     # <-- new named volume for sqlite
      - ./backend/token.json:/app/backend/token.json
      - ./backend/credentials.json:/app/backend/credentials.json
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
